version: '3.8'

services:
  blazorapp:
    container_name: BlazorMovieWebApp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__BlazorWebAppMoviesContext=Host=postgres;Database=BlazorWebAppMovies;Username=test;Password=test
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=BlazorWebAppMovies
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test" ]
      interval: 10s
      timeout: 5s
      retries: 5
  moviesRedis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  postgres_data: